---
driver:
  name: vagrant

platforms:
  # ====================== Ubuntu =====================
  - name: ubuntu-14.04
    require_chef_omnibus: 12.21.20
    run_list:
      - recipe[apt]
      - recipe[build-essential]
  - name: ubuntu-16.04
    require_chef_omnibus: 12.21.20
    run_list:
      - recipe[apt]
      - recipe[build-essential]
  - name: ubuntu-14.04
    require_chef_omnibus: 13.5.3
    run_list:
      - recipe[apt]
      - recipe[build-essential]
  - name: ubuntu-16.04
    require_chef_omnibus: 13.5.3
    run_list:
      - recipe[apt]
      - recipe[build-essential]
  # ====================== CentOS =====================
  - name: centos-6.9
    require_chef_omnibus: 12.21.20
    run_list:
      - recipe[build-essential]
  - name: centos-7
    require_chef_omnibus: 12.21.20
    run_list:
      - recipe[build-essential]
  - name: centos-6.9
    require_chef_omnibus: 12.21.20
    run_list:
      - recipe[build-essential]
  - name: centos-7
    require_chef_omnibus: 12.21.20
    run_list:
      - recipe[build-essential]
  - name: oracle-7.3
    run_list:
      - recipe[build-essential]

suites:
  - name: system_python
    run_list:
      - recipe[pyenv::system]
    attributes:
      pyenv:
        pythons:
          - 2.7.6
          - 3.6.2
        global: 2.7.6

  - name: user_python
    run_list:
      - recipe[pyenv::user]
    attributes:
      pyenv:
        user_installs:
          - user: 'vagrant'
            pythons:
              - 2.7.6
              - 3.6.0
            global: 2.7.6
