---
driver:
  name: vagrant

platforms:
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
  - recipe[build-essential]
- name: centos-6.5
  run_list:
  - recipe[build-essential]
- name: centos-6.4
  run_list:
  - recipe[build-essential]

suites:
- name: system_python
  run_list:
  - recipe[pyenv::system]
  attributes:
    pyenv:
      pythons:
        - 2.7.6
        - 2.6.9
        - 3.4.0
      global: 2.7.6

- name: user_python
  run_list:
  - recipe[pyenv::user]
  attributes:
    pyenv:
      user_installs:
        - user: 'vagrant'
          pythons:
            - 2.7.6
            - 2.6.9
            - 3.4.0
          global: 2.7.6
