---
driver:
  name: vagrant
  provider: virtualbox

provisioner:
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || "current" %>
  install_strategy: once
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: debian-8
  - name: debian-9
  - name: centos-6
  - name: centos-7
  - name: amazon
    driver:
      box: generic/rhel8
  - name: oracle-7
  - name: fedora-29
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: opensuse-leap-42

suites:
  # - name: gem
  #   run_list:
  #     - recipe[test::dokken]
  #     - recipe[test::gem]
  #   includes: [centos-7]
  - name: system_install
    run_list:
      - recipe[test::system_install]
  - name: user_install
    run_list:
      - recipe[test::dokken]
      - recipe[test::user_install]
