driver:
  name: dokken
  chef_version: <%= ENV['CHEF_VERSION'] || "current" %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-8
  driver:
    image: dokken/debian-8
    intermediate_instructions:
       - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    intermediate_instructions:
       - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6

- name: centos-7
  driver:
    image: dokken/centos-7

- name: amazon-linux
  driver:
    image: dokken/amazonlinux

- name: oracle-linux-7.3
  driver:
    image: oraclelinux:7.3

- name: fedora-latest
  driver:
    image: dokken/fedora-latest

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    intermediate_instructions:
       - RUN /usr/bin/apt-get update

# - name: ubuntu-18.04
#   driver:
#     image: dokken/ubuntu-18.04
#     intermediate_instructions:
#        - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    intermediate_instructions:
    - RUN zypper --non-interactive install sudo

suites:
  # - name: gem
  #   run_list:
  #     - recipe[test::dokken]
  #     - recipe[test::gem]
  #   includes: [centos-7]
  # - name: global
  #   run_list: recipe[test::global]
  - name: system_install
    run_list:
      - recipe[build-essential]
      - recipe[test::system_install]
  # - name: user_install
  #   run_list:
  #     - recipe[test::dokken]
  #     - recipe[test::user_install]
