driver:
  name: dokken
  chef_version: <%= ENV['CHEF_VERSION'] || "current" %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: debian-8
  driver:
    image: debian:8
    intermediate_instructions:
       - RUN /usr/bin/apt-get update
       - RUN /usr/bin/apt-get install sudo -y

- name: debian-9
  driver:
    image: debian:9
    intermediate_instructions:
       - RUN /usr/bin/apt-get update
       - RUN /usr/bin/apt-get install sudo -y

- name: centos-6
  driver:
    image: centos:6
    intermediate_instructions:
      - RUN yum -y install sudo

- name: centos-7
  driver:
    image: centos:7
    intermediate_instructions:
      - RUN yum -y install sudo

- name: amazon-linux
  driver:
    image: amazonlinux
    intermediate_instructions:
      - RUN yum -y install sudo

- name: oracle-linux
  driver:
    image: oraclelinux:7
    intermediate_instructions:
      - RUN yum -y install sudo

- name: fedora
  driver:
    image: fedora:27
    intermediate_instructions:
      - RUN dnf -y install sudo

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    intermediate_instructions:
       - RUN /usr/bin/apt-get update
       - RUN /usr/bin/apt-get install sudo -y

- name: ubuntu-18.04
  driver:
    image: ubuntu:18.04
    intermediate_instructions:
       - RUN /usr/bin/apt-get update
       - RUN /usr/bin/apt-get install sudo -y

- name: opensuse
  driver:
    image: opensuse:42.3
    intermediate_instructions:
    - RUN zypper --non-interactive install sudo

- name: opensuse-leap
  driver:
    image: opensuse:leap
    intermediate_instructions:
    - RUN zypper --non-interactive install sudo

suites:
  # - name: gem
  #   run_list:
  #     - recipe[test::dokken]
  #     - recipe[test::gem]
  #   includes: [centos-7]
  - name: system_install
    run_list:
      - recipe[build-essential]
      - recipe[test::system_install]
  - name: user_install
    run_list:
      - recipe[build-essential]
      - recipe[test::dokken]
      - recipe[test::user_install]
