driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9
  - name: centos-7.3
  - name: fedora-25
  - name: debian-8.8
  - name: debian-9.0
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12
    provisioner:
      require_chef_omnibus: 12
    driver_config:
      box: bento/ubuntu-16.04

suites:
  # - name: gem
  #   run_list: recipe[test::gem]
  #   includes: [ubuntu-16.04]
  # - name: global
  #   run_list: recipe[test::global]
  - name: system_install
    run_list:
      - recipe[apt]
      - recipe[build-essential]
      - recipe[test::system_install]
    includes: [ubuntu-16.04]
  # - name: user_install
  #   run_list: recipe[test::user_install]
  #   includes: [ubuntu-16.04]
