---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.21.20

verifier:
  name: inspec

platforms:
  # ====================== Ubuntu =====================
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
      - recipe[build-essential]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
      - recipe[build-essential]
  # ====================== CentOS =====================
  - name: centos-6.9
    run_list:
      - recipe[build-essential]
  - name: centos-7
    run_list:
      - recipe[build-essential]
  - name: oracle-7.3
    run_list:
      - recipe[build-essential]

suites:
  - name: system_python
    run_list:
      - recipe[pyenv::system]
    verifier:
      inspec_tests:
        - test/smoke/system
    attributes:
      pyenv:
        pythons:
          - 2.7.6
          - 3.6.0
        global: 2.7.6

  - name: user_python
    run_list:
      - recipe[pyenv::user]
    verifier:
      inspec_tests:
        - test/smoke/user
    attributes:
      pyenv:
        user_installs:
          - user: kitchen
            pythons:
              - 2.7.6
              - 3.6.0
            global: 2.7.6
