dist: trusty
cache: bundler
sudo: required

language: ruby

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0

services:
  - docker

before_install:
  - gem install bundler
  - gem update --system

bundler_args: --jobs 7 --retry 3

env:
  matrix:
    # - CHEF_VERSION=12.9.38
    # - CHEF_VERSION=12.22.1
    # - CHEF_VERSION=13.8.5
    # - INSTANCE=gem-centos-7
    # - INSTANCE=global-debian-8
    # - INSTANCE=global-debian-9
    # - INSTANCE=global-centos-7
    # - INSTANCE=global-centos-7 CHEF_VERSION=12.9.41
    # - INSTANCE=global-fedora-latest
    # - INSTANCE=global-ubuntu-1604
    # - INSTANCE=global-ubuntu-1804
    # - INSTANCE=global-opensuse-leap
    - INSTANCE=system-install-debian-8
    - INSTANCE=system-install-debian-9
    - INSTANCE=system-install-centos-6
    - INSTANCE=system-install-centos-7
    - INSTANCE=system-install-fedora-latest
    - INSTANCE=system-install-ubuntu-1604
    - INSTANCE=system-install-ubuntu-1804
    - INSTANCE=system-install-opensuse-leap
    # - INSTANCE=user-install-debian-8
    # - INSTANCE=user-install-debian-9
    # - INSTANCE=user-install-centos-7
    # - INSTANCE=user-install-fedora-latest
    # - INSTANCE=user-install-ubuntu-1404
    # - INSTANCE=user-install-ubuntu-1604
    # - INSTANCE=user-install-ubuntu-1804
    # - INSTANCE=user-install-opensuse-leap

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

# matrix:
#   include:
#     - script:
#       - chef exec delivery local all
#       env: UNIT_AND_LINT=1

notifications:
  slack:
    rooms:
      - ${SLACK_NOTIFY}
